<?php

/**
 * Global variable used to transfer the form to the hook.
 */

$_insightly_drupal_form = 0;

/**
 * Adds the submit hook to the form.
 */
function insightly_drupal_form_entityform_edit_form_alter(&$form, &$form_state) {
  $chosen_forms = variable_get('insightly_drupal_chosen_forms');
  if ($chosen_forms[$form['#bundle']] !== 0) {
    global $_insightly_drupal_form; $_insightly_drupal_form = $form;
    $form['actions']['submit']['#submit'] = array('entityform_edit_form_submit', 'insightly_drupal_submithook');
  }
}

/**
 * Sends the data from the form to Insightly.
 */
function insightly_drupal_submithook() {
  global $_insightly_drupal_form;

  $chosen_fields = variable_get('insightly_drupal_chosen_fields', 0);
  $lang = $_insightly_drupal_form['field_last_name']['#language'];

  if ($chosen_fields['Last Name'] !== 0) {
    $last_name = $_insightly_drupal_form['#entity']->field_last_name[$lang][0]['value'];
  }
  else {
    $last_name = 'N/A';
  }

  if ($chosen_fields['First Name'] !== 0) {
    $first_name = $_insightly_drupal_form['#entity']->field_first_name[$lang][0]['value'];
  }
  else {
    $first_name = 'N/A';
  }

  if ($chosen_fields['Phone Number'] !== 0) {
    $phone_number = $_insightly_drupal_form['#entity']->field_phone_number[$lang][0]['value'];
  }
  else {
    $phone_number = 'N/A';
  }

  if ($chosen_fields['Email'] !== 0) {
    $email_address = $_insightly_drupal_form['#entity']->field_email_address[$lang][0]['value'];
  }
  else {
    $email_address = 'N/A';
  }

  date_default_timezone_set('UTC');
  $date = date('Y-m-d H:m:s');

  $contact = '{"CONTACT_ID":0,"SALUTATION":null,"FIRST_NAME":"' . $first_name . '","LAST_NAME":"' . $last_name . '","BACKGROUND":null,"IMAGE_URL":"http://s3.amazonaws.com/insightly.userfiles/367601/","DEFAULT_LINKED_ORGANISATION":null,"DATE_CREATED_UTC":"' . $date . '","DATE_UPDATED_UTC":"' . $date . '","VISIBLE_TO":"EVERYONE","VISIBLE_TEAM_ID":null,"VISIBLE_USER_IDS":null,"CUSTOMFIELDS":[],"ADDRESSES":[],"CONTACTINFOS":[{"CONTACT_INFO_ID":0,"TYPE":"PHONE","SUBTYPE":"Work","LABEL":null,"DETAIL":"' . $phone_number . '"}, {"CONTACT_INFO_ID":0,"TYPE":"EMAIL","SUBTYPE":"Work","LABEL":null,"DETAIL":"'   . $email_address . '"}],"DATES":[],"TAGS":[],"LINKS":[],"CONTACTLINKS":[],"EMAILLINKS":null}';

  $url = 'https://api.insight.ly/v2.1/Contacts';
  $ch = curl_init($url);

  $user = variable_get('insightly_drupal_apikey', 0);
  if ($user == 0) {
    watchdog('insightly_drupal', 'API key not set!');
  }
  $user = base64_encode($user);

  curl_setopt($ch,
    CURLOPT_HTTPHEADER,
    array('Content-Type: application/json',
      'Authorization: Basic ' . $user));
  curl_setopt($ch, CURLOPT_HEADER, 0);
  curl_setopt($ch, CURLOPT_TIMEOUT, 30);
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

  curl_setopt($ch, CURLOPT_POST, 1);
  curl_setopt($ch, CURLOPT_POSTFIELDS, $contact);

  curl_exec($ch);
  curl_error($ch);

  curl_close($ch);
}

/**
 * Calls the Configure form.
 */
function insightly_drupal_menu() {
  $items = array();
  $items['admin/config/content/insightly_drupal'] = array(
    'title' => 'Insightly Integration for Drupal',
    'description' => 'Configuration for Insightly Integration for Drupal module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('insightly_drupal_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Settings form.
 */
function insightly_drupal_form($form, &$form_state) {
  $info = entity_get_info('entityform');
  $keys = array_keys($info['bundles']);

  $form['insightly_drupal_apikey'] = array(
    '#type' => 'textfield',
    '#title' => t('Your Insight.ly API key'),
    '#default_value' => variable_get('insightly_drupal_apikey', 0),
    '#size' => 60,
    '#maxlength' => 60,
    '#description' => t('Your Insight.ly API key used in authentication.'),
    '#required' => TRUE,
  );
  $form['insightly_drupal_chosen_fields'] = array(
    '#type' => 'checkboxes',
    '#options' => drupal_map_assoc(array(
      t('Last Name'),
      t('First Name'),
      t('Email'),
      t('Phone Number'))),
    '#title' => t('Select the fields to be sent to Insight.ly.'),
    '#default_value' => variable_get('insightly_drupal_chosen_fields', array(
      t('Last Name'),
      t('First Name'),
      t('Email'),
      t('Phone Number'))),
    '#required' => TRUE,
  );
  $form['insightly_drupal_chosen_forms'] = array(
    '#type' => 'checkboxes',
    '#options' => drupal_map_assoc($keys),
    '#title' => 'Select the forms where Insightly Integration for Drupal is used.',
    '#default_value' => variable_get('insightly_drupal_chosen_forms', $keys),
  );
  return system_settings_form($form);
}
